# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35170261f0e0052c89b6c39c86511d9fff0f1e080be04fb74ca8cd2e23cd7eff70b4e254041cc544578fade1e5debe156e244787961a9c387f88e1a19182afcb

test:
  secret_key_base: 038875553158c54fe23982786e409429b1e2ca0f81a417757eb27412872ba9cb5a1ec0ba9af3950320016e3504696a83516e17c4aaf3fe4f68bb4feed0a1ddfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
